source "https://rubygems.org"

ruby ">= 3.1.0"

gem "rails", "~> 7.1"
gem "sqlite3", "~> 1.7"
gem "puma", ">= 5.0"
gem "sprockets-rails"
gem "jbuilder"
gem "tzinfo-data", platforms: %i[windows jruby]
gem "bootsnap", require: false

group :development do
  gem "web-console"
end

group :test do
  gem "capybara"
  gem "selenium-webdriver"
end
